// Code generated by entc, DO NOT EDIT.

package patient

const (
	// Label holds the string label denoting the patient type in the database.
	Label = "patient"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldPatientAge holds the string denoting the patient_age field in the database.
	FieldPatientAge = "patient_age"

	// EdgeAntenatals holds the string denoting the antenatals edge name in mutations.
	EdgeAntenatals = "antenatals"

	// Table holds the table name of the patient in the database.
	Table = "patients"
	// AntenatalsTable is the table the holds the antenatals relation/edge.
	AntenatalsTable = "antenatals"
	// AntenatalsInverseTable is the table name for the Antenatal entity.
	// It exists in this package in order to avoid circular dependency with the "antenatal" package.
	AntenatalsInverseTable = "antenatals"
	// AntenatalsColumn is the table column denoting the antenatals relation/edge.
	AntenatalsColumn = "patient_id"
)

// Columns holds all SQL columns for patient fields.
var Columns = []string{
	FieldID,
	FieldPatientName,
	FieldPatientAge,
}

var (
	// PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
	// PatientAgeValidator is a validator for the "patient_age" field. It is called by the builders before save.
	PatientAgeValidator func(int) error
)
