// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/F12aPPy/app/ent/antenatal"
	"github.com/F12aPPy/app/ent/babystatus"
	"github.com/F12aPPy/app/ent/patient"
	"github.com/F12aPPy/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
)

// Antenatal is the model entity for the Antenatal schema.
type Antenatal struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// AddedTime holds the value of the "added_time" field.
	AddedTime time.Time `json:"added_time,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AntenatalQuery when eager-loading is set.
	Edges         AntenatalEdges `json:"edges"`
	babystatus_id *int
	patient_id    *int
	owner_id      *int
}

// AntenatalEdges holds the relations/edges for other nodes in the graph.
type AntenatalEdges struct {
	// User holds the value of the user edge.
	User *User
	// Patient holds the value of the patient edge.
	Patient *Patient
	// Babystatus holds the value of the babystatus edge.
	Babystatus *Babystatus
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AntenatalEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// The edge user was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PatientOrErr returns the Patient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AntenatalEdges) PatientOrErr() (*Patient, error) {
	if e.loadedTypes[1] {
		if e.Patient == nil {
			// The edge patient was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: patient.Label}
		}
		return e.Patient, nil
	}
	return nil, &NotLoadedError{edge: "patient"}
}

// BabystatusOrErr returns the Babystatus value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AntenatalEdges) BabystatusOrErr() (*Babystatus, error) {
	if e.loadedTypes[2] {
		if e.Babystatus == nil {
			// The edge babystatus was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: babystatus.Label}
		}
		return e.Babystatus, nil
	}
	return nil, &NotLoadedError{edge: "babystatus"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Antenatal) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullTime{},  // added_time
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Antenatal) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // babystatus_id
		&sql.NullInt64{}, // patient_id
		&sql.NullInt64{}, // owner_id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Antenatal fields.
func (a *Antenatal) assignValues(values ...interface{}) error {
	if m, n := len(values), len(antenatal.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	a.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field added_time", values[0])
	} else if value.Valid {
		a.AddedTime = value.Time
	}
	values = values[1:]
	if len(values) == len(antenatal.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field babystatus_id", value)
		} else if value.Valid {
			a.babystatus_id = new(int)
			*a.babystatus_id = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field patient_id", value)
		} else if value.Valid {
			a.patient_id = new(int)
			*a.patient_id = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field owner_id", value)
		} else if value.Valid {
			a.owner_id = new(int)
			*a.owner_id = int(value.Int64)
		}
	}
	return nil
}

// QueryUser queries the user edge of the Antenatal.
func (a *Antenatal) QueryUser() *UserQuery {
	return (&AntenatalClient{config: a.config}).QueryUser(a)
}

// QueryPatient queries the patient edge of the Antenatal.
func (a *Antenatal) QueryPatient() *PatientQuery {
	return (&AntenatalClient{config: a.config}).QueryPatient(a)
}

// QueryBabystatus queries the babystatus edge of the Antenatal.
func (a *Antenatal) QueryBabystatus() *BabystatusQuery {
	return (&AntenatalClient{config: a.config}).QueryBabystatus(a)
}

// Update returns a builder for updating this Antenatal.
// Note that, you need to call Antenatal.Unwrap() before calling this method, if this Antenatal
// was returned from a transaction, and the transaction was committed or rolled back.
func (a *Antenatal) Update() *AntenatalUpdateOne {
	return (&AntenatalClient{config: a.config}).UpdateOne(a)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (a *Antenatal) Unwrap() *Antenatal {
	tx, ok := a.config.driver.(*txDriver)
	if !ok {
		panic("ent: Antenatal is not a transactional entity")
	}
	a.config.driver = tx.drv
	return a
}

// String implements the fmt.Stringer.
func (a *Antenatal) String() string {
	var builder strings.Builder
	builder.WriteString("Antenatal(")
	builder.WriteString(fmt.Sprintf("id=%v", a.ID))
	builder.WriteString(", added_time=")
	builder.WriteString(a.AddedTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Antenatals is a parsable slice of Antenatal.
type Antenatals []*Antenatal

func (a Antenatals) config(cfg config) {
	for _i := range a {
		a[_i].config = cfg
	}
}
