// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/F12aPPy/app/ent/babystatus"
	"github.com/F12aPPy/app/ent/patient"
	"github.com/F12aPPy/app/ent/schema"
	"github.com/F12aPPy/app/ent/user"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	babystatusFields := schema.Babystatus{}.Fields()
	_ = babystatusFields
	// babystatusDescBabystatusName is the schema descriptor for babystatus_name field.
	babystatusDescBabystatusName := babystatusFields[0].Descriptor()
	// babystatus.BabystatusNameValidator is a validator for the "babystatus_name" field. It is called by the builders before save.
	babystatus.BabystatusNameValidator = babystatusDescBabystatusName.Validators[0].(func(string) error)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescPatientName is the schema descriptor for patient_name field.
	patientDescPatientName := patientFields[0].Descriptor()
	// patient.PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	patient.PatientNameValidator = patientDescPatientName.Validators[0].(func(string) error)
	// patientDescPatientAge is the schema descriptor for patient_age field.
	patientDescPatientAge := patientFields[1].Descriptor()
	// patient.PatientAgeValidator is a validator for the "patient_age" field. It is called by the builders before save.
	patient.PatientAgeValidator = patientDescPatientAge.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[0].Descriptor()
	// user.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
	// userDescUserEmail is the schema descriptor for user_email field.
	userDescUserEmail := userFields[1].Descriptor()
	// user.UserEmailValidator is a validator for the "user_email" field. It is called by the builders before save.
	user.UserEmailValidator = userDescUserEmail.Validators[0].(func(string) error)
}
